# Generated by Django 6.0.2 on 2026-02-06 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(unique=True)),
                ('days_to_childbirth', models.IntegerField()),
                ('baby_image', models.URLField()),
                ('baby_size', models.FloatField(help_text='Size in cm')),
                ('baby_weight', models.FloatField(help_text='Weight in grams')),
                ('baby_analogy', models.CharField(max_length=255)),
                ('baby_activity', models.TextField()),
                ('baby_development', models.TextField()),
                ('interesting_fact', models.TextField()),
                ('daily_tip', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='MomFeeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling_state', models.CharField(max_length=255)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feelings', to='journey.weekdata')),
            ],
        ),
        migrations.CreateModel(
            name='ComfortTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('tip', models.TextField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comfort_tips', to='journey.weekdata')),
            ],
        ),
    ]
