# Generated by Django 6.0.2 on 2026-02-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdata',
            name='daily_tip',
        ),
        migrations.RemoveField(
            model_name='weekdata',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='weekdata',
            name='mom_daily_tips',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='momfeeling',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mom_feelings', to='journey.weekdata'),
        ),
        migrations.AlterField(
            model_name='weekdata',
            name='baby_analogy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weekdata',
            name='baby_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weekdata',
            name='baby_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weekdata',
            name='days_to_childbirth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='comforttip',
            unique_together={('week', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='momfeeling',
            unique_together={('week', 'feeling_state')},
        ),
    ]
