# Generated by Django 6.0.2 on 2026-02-11 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.CharField(default=datetime.date(2026, 2, 11), max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
